# 프로젝트 설정
sonar.projectKey=sqp_6c2bd0d4adf6e1d4a817b2690905ee8c4ce0c456
sonar.qualitygate.wait=true
sonar.projectName=jk-bizcenter-fe-web

# 소스 경로 (코드 품질 검사용 - 전체 src 폴더)
sonar.exclusions=**/*.html, **/*stories.tsx, server.mjs, scripts/**, e2e/**, docs/**, **/*.tsx
sonar.sources=src
sonar.sourceEncoding=UTF-8
sonar.typescript.tsconfigPath=tsconfig-sonar.json

# 중복 검사 제외 (데이터 파일, 상수 파일, API 스키마)
sonar.cpd.exclusions=**/*constants.ts, **/schemas/**, **/*.types.ts, src/core/**/*

## 테스트 커버리지
sonar.typescript.lcov.reportPaths=coverage/lcov.info
sonar.tests=src
sonar.test.inclusions=src/**/*.test.ts
sonar.coverage.exclusions=**/*.d.ts, **/*.tsx, **/*.css.ts, **/*.config.*, **/*.spec.ts, **/*.types.ts, *.mjs, src/middleware.ts, src/app/**/*.ts, src/shared/fetch/*.ts, src/shared/config/*.ts, src/**/api/*.ts, src/shared/utils/pdf-utils.ts, src/shared/utils/image-splitter.ts, src/**/constants/**/*.ts, src/core/**/*,  **/domain/entities.ts, **/domain/*/entities.ts

# 규칙 제외 설정
# TODO 주석 code smell 제외
# Cognitive Complexity 체크 제외 (환경설정 파일)
# Union Type to Type Alias 체크 제외 (API 스키마 파일)
sonar.issue.ignore.multicriteria=e1,e2,e3
sonar.issue.ignore.multicriteria.e1.ruleKey=typescript:S1135
sonar.issue.ignore.multicriteria.e1.resourceKey=**/*
sonar.issue.ignore.multicriteria.e2.ruleKey=typescript:S3776
sonar.issue.ignore.multicriteria.e2.resourceKey=src/shared/config/**/*.ts
sonar.issue.ignore.multicriteria.e3.ruleKey=typescript:S4323
sonar.issue.ignore.multicriteria.e3.resourceKey=src/shared/types/api/**/schemas/**/*.ts

# SonarQube 서버 정보
sonar.host.url=https://sqube.mgt.comm.jobkorea.co.kr
sonar.login=squ_22dae8092a2c0cc50f9ca094ac7a8e6fa108353e
