#!/usr/bin/env node
import fs from 'fs';
import path from 'path';

const ROOT_DIR = process.cwd();
const FIGMA_VARIABLES_PATH = path.join(ROOT_DIR, 'figma.variables.json');
const OUTPUT_CSS_PATH = path.join(ROOT_DIR, 'src/app/design-tokens.css');

/**
 * camelCase를 kebab-case로 변환
 * paletteBlueBlue500 -> palette-blue-blue-500
 */
function toKebabCase(str) {
  return str
    .replace(/([a-z0-9])([A-Z])/g, '$1-$2')
    .replace(/([A-Z])([A-Z][a-z])/g, '$1-$2')
    .toLowerCase();
}

/**
 * CSS 변수명 생성
 */
function toCssVarName(key) {
  return `--${toKebabCase(key)}`;
}

/**
 * 값이 숫자인지 확인
 */
function isNumber(value) {
  return typeof value === 'number';
}

/**
 * primitive 토큰을 CSS 변수로 변환
 */
function generatePrimitiveTokens(primitiveTokens) {
  const cssVars = [];

  for (const [key, value] of Object.entries(primitiveTokens)) {
    const varName = toCssVarName(key);
    let cssValue = value;

    if (isNumber(value) && !key.toLowerCase().includes('opacity')) {
      cssValue = `${value}px`;
    }

    cssVars.push(`  ${varName}: ${cssValue};`);
  }

  return cssVars.join('\n');
}

/**
 * component 테마 토큰을 CSS 변수로 변환
 */
function generateThemeTokens(themeName, themeTokens) {
  const cssVars = [];

  for (const [key, value] of Object.entries(themeTokens)) {
    const varName = toCssVarName(key);
    let cssValue = value;

    if (isNumber(value) && !key.toLowerCase().includes('opacity')) {
      cssValue = `${value}px`;
    }

    cssVars.push(`  ${varName}: ${cssValue};`);
  }

  return cssVars.join('\n');
}

/**
 * design-tokens.css 파일 생성
 */
function generateCssFile(figmaVariables) {
  const { component, primitive } = figmaVariables;

  let cssContent = `/**
 * Design Tokens - Auto-generated from figma.variables.json
 * DO NOT EDIT THIS FILE MANUALLY
 * Generated at: ${new Date().toISOString()}
 */

@layer base {
  /* ===== Primitive Tokens ===== */
  :root {
${generatePrimitiveTokens(primitive)}
  }

`;

  // 각 테마별 CSS 변수 생성
  for (const [themeName, themeTokens] of Object.entries(component)) {
    cssContent += `  /* ===== Theme: ${themeName} ===== */
  [data-jds-theme="${themeName}"] {
${generateThemeTokens(themeName, themeTokens)}
  }

`;
  }

  cssContent += '}\n';

  return cssContent;
}

/**
 * 메인 실행 함수
 */
async function main() {
  try {
    console.log('🚀 Starting design tokens generation...\n');

    // figma.variables.json 읽기
    console.log('📖 Reading figma.variables.json...');
    const figmaVariables = JSON.parse(fs.readFileSync(FIGMA_VARIABLES_PATH, 'utf-8'));
    console.log('✅ Figma variables loaded\n');

    // CSS 파일 생성
    console.log('🎨 Generating design-tokens.css...');
    const cssContent = generateCssFile(figmaVariables);

    const cssDir = path.dirname(OUTPUT_CSS_PATH);
    if (!fs.existsSync(cssDir)) {
      fs.mkdirSync(cssDir, { recursive: true });
    }

    fs.writeFileSync(OUTPUT_CSS_PATH, cssContent, 'utf-8');
    console.log(`✅ CSS file generated: ${OUTPUT_CSS_PATH}\n`);

    console.log('🎉 Design tokens generation completed successfully!');
    console.log('\n📝 Next steps:');
    console.log('   1. Import design-tokens.css in your app');
    console.log('   2. Use tokens with data-jds-theme attribute:');
    console.log('      <div data-jds-theme="jobkorea">...</div>');
    console.log('      <div data-jds-theme="albamon">...</div>');
  } catch (error) {
    console.error('❌ Error generating design tokens:', error);
    process.exit(1);
  }
}

main();
